### PR TITLE
vps code fully generated by swagger

### PR DESCRIPTION
**Pull request by zhanggbj**
Hi dr.max @maximilien ,

These are vps code fully generated by swagger. Thanks.

/cc @mattcui @jianqiu

### CODE REVIEW

**Comment by maximilien** [comment]
Hi, @zhanggbj, 

Looks good. Just wondering if there is way to make clear that this is from generated code? Like we did when I was in Beijing, add `geneated` top level directory? Or perhaps have all generated code in that top level and then use some symbolic links if you need the `vps/**` and `bms/**` directories at the top level as well.

Let me know. Best,

Max

**Comment by zhanggbj** [comment]
Hi dr.max @maximilien ,

Moved files generated by swagger to generated/. Thanks.

**Review by maximilien — APPROVED** [review]
Thx

**Comment by maximilien** [comment]
Cool. Merging 👍

**Pull request merged**
